# Generated by Django 4.1.4 on 2024-01-06 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail/')),
                ('selected_game', models.CharField(blank=True, max_length=100, null=True)),
                ('room_member', models.CharField(blank=True, max_length=100, null=True)),
                ('tornament_dt', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 6, 20, 49, 37, 358757), null=True)),
                ('start_tm', models.TimeField(blank=True, null=True)),
                ('end_tm', models.TimeField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('room_password', models.CharField(blank=True, max_length=100, null=True)),
                ('game_type', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_team', models.CharField(blank=True, max_length=100, null=True)),
                ('room_joining', models.CharField(blank=True, max_length=100, null=True)),
                ('room_joining_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('game_map', models.CharField(blank=True, max_length=100, null=True)),
                ('game_room_id', models.CharField(blank=True, max_length=100, null=True)),
                ('game_room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('game_room_type_pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tornament_app.userdetails')),
            ],
        ),
    ]
