# Generated by Django 4.1.4 on 2024-01-06 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tornament_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_master',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 1, 54, 27, 131583), null=True),
        ),
        migrations.AlterField(
            model_name='room_master',
            name='tornament_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 1, 54, 27, 131583), null=True),
        ),
    ]
