# Generated by Django 4.1.4 on 2024-01-06 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tornament_app', '0002_room_master_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 1, 55, 2, 850478), null=True),
        ),
        migrations.AlterField(
            model_name='room_master',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 1, 55, 2, 850478), null=True),
        ),
        migrations.AlterField(
            model_name='room_master',
            name='tornament_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 1, 55, 2, 850478), null=True),
        ),
    ]
