# Generated by Django 4.1.4 on 2024-01-07 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tornament_app', '0003_userdetails_created_dt_alter_room_master_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_master',
            name='available_seats',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room_master',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 1, 0, 138493), null=True),
        ),
        migrations.AlterField(
            model_name='room_master',
            name='tornament_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 1, 0, 138493), null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 1, 0, 138493), null=True),
        ),
        migrations.CreateModel(
            name='JoinRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tornament_app.room_master')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tornament_app.userdetails')),
            ],
        ),
    ]
