# Generated by Django 4.1.4 on 2024-01-07 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tornament_app', '0004_room_master_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinroom',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 1, 28, 256937), null=True),
        ),
        migrations.AlterField(
            model_name='room_master',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 1, 28, 256937), null=True),
        ),
        migrations.AlterField(
            model_name='room_master',
            name='tornament_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 1, 28, 256937), null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 7, 19, 1, 28, 256937), null=True),
        ),
    ]
